### ISSUE TITLE
The definition sub_128 in cropping.py and the datalist of training and testing data

### ISSUE THREAD

**Issue by dyh127** [ReubenDo/U-HVED#5]
Hi,

I find this work focuses on an interesting problem that is hetero-modality images segmentation. Besides, the proposed method is also enlightening.

But, when I try to preprocess the data, I find the function 'sub_128' in cropping.py is not defined. So would you like to share the code of 'sub_128'.
Besides, in you paper, the training set of Brats2018 has been split into training, validatation and testing set. So would you like to share the data split list with me. So that, I can use this data to do further researches on the hetero-modality segmentation.

Looking forward to your reply, thanks a lot.

**Comment by ReubenDo** [comment]
Hi,

Thanks for your interest. 

`cropping.py` has been updated.

Following our private discussion, I closed the issue.

Regards,
Reuben

**Comment by GuojingZhao** [comment]
Hi ReubenDo,

I also have the same situation with @dyh127 .  The BraTS2018 dataset was split into three folders by yourself.  I want continue do more researches in this task. Could you share the detailed list with me?  Thanks.
