### ISSUE TITLE
What will happen to the encoder if one modality is missing?

### ISSUE THREAD

**Issue by ghost** [ReubenDo/U-HVED#7]
Thanks for your interesting work and the code, I have a small question:
If one or some modality is missing, what will happen to its encoder? It'll not be used or a zero image is used as input? Can you show the according code? Thank you very much.

**Comment by ReubenDo** [comment]
Hi,

Sorry, I just saw this issue.

There is a different encoder for each imaging modality. The outputs of the encoders correspond to two normal distribution parameters (mean and variance). The modalities-specific means and variances are then combined using Eq. (4). The fusion operation (weighted average) allows for missing modality-specific encodings. In particular, if a modality is missing, nothing is fed to the modality-specific embedding.

I hope this helps.
Regards,
Reuben
