### ISSUE TITLE
Problems when trying to train the model

### ISSUE THREAD

**Issue by QiushiYang** [ReubenDo/U-HVED#8]
Thank you for sharing the codes. I meet some problems when training models.
(1) I try to train the model using net_train command but meet the error "ValueError: application: Could not import object"U_HVEDApplication" from "application" ". It seems it can't call the Class U_HVEDApplication? (I used tensorflow-1.13, but maybe there is little difference between version-1.13 and version-1.12 I guess.)
(2) Besides, it seems there are some training hyperparameters not been shown in this repo, for example, action_param.validation_every_n,  action_param.vars_to_freeze, etc. Wonder is there any script not put into the repo?
Many thanks!

**Comment by ReubenDo** [comment]
Dear Qiushi,

(1) The code has only been tested using `tensorflow-gpu==1.12.2` and `niftynet==0.5.0`. The two packages are now depreciated and no more support is provided for NiftyNet. I don't plan to update the code. Can you please try with these two versions?

(2) All the hyperparameters are defined in `extensions/u_hved/config.ini`. The other hyper-parameters are the ones used by default in NiftyNet 0.5.0: https://niftynet.readthedocs.io/en/v0.5.0/config_spec.html

Regards,
Reuben
